spring:
  application:
    name: redis-demo
  main:
    banner-mode: off
  profiles:
    active: dev
  redis:
    host: localhost

logging:
  level:
    org.apache.tomcat: warn
    org.apache.catalina: warn
    org.apache.coyote: warn
    org.springframework: warn
